services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    container_name: bar-estoque-api
    environment:
      SPRING_DATASOURCE_URL: jdbc:oracle:thin:@//oracle:1521/FREEPDB1
      SPRING_DATASOURCE_USERNAME: ${APP_USER}
      SPRING_DATASOURCE_PASSWORD: ${APP_USER_PASSWORD}
    depends_on:
      oracle:
        condition: service_healthy
    
  oracle:
    image: gvenzl/oracle-free:23.5-slim
    container_name: oracle-free
    environment:
      APP_USER: ${APP_USER}                
      APP_USER_PASSWORD: ${APP_USER_PASSWORD}
      ORACLE_PASSWORD: ${ORACLE_PASSWORD}
    ports:
      - "1522:1521"      
    volumes:
      - oradata:/opt/oracle/oradata
    healthcheck:
      test: ["CMD", "healthcheck.sh"]
      interval: 15s
      timeout: 5s
      retries: 10
volumes:
  oradata:
